<?php
/**
 * @var $this Profileolabs_Shoppingflux_Block_Export_Adminhtml_Product
 * @see Profileolabs_Shoppingflux_Block_Export_Adminhtml_Product
 */
?>
<div class="content-header">
<table cellspacing="0">
    <tr>
        <td style="width:50%;"><h3 class="icon-head head-products"><?php echo Mage::helper('profileolabs_shoppingflux')->__('Select product to export to ShoppingFlux') ?></h3></td>
        <td class="a-right">
            <?php echo $this->getButtonsHtml() ?>
        </td>
    </tr>
</table>
</div>
<?php if( !$this->isSingleStoreMode() ): ?>
<?php echo $this->getChildHtml('store_switcher');?>
<?php endif;?>
<div>
    <?php echo $this->getGridHtml() ?>
</div>
