<?php $flowModel = $this->getFlowModel()?>
<style type="text/css" >
    ul { list-style-type:none; padding:0; margin:0; }
    li { margin-left:0; border:1px solid #ccc; margin:2px; padding:2px 2px 2px 2px; font:normal 12px sans-serif; }
    img { margin-right:5px; }
</style>
<script type="text/javascript">
    var FORM_KEY = "<?php echo $this->getFormKey();?>";
</script>
    <ul>
        <li>
            <img src="<?php echo $this->getSkinUrl('images/note_msg_icon.gif')?>" class="v-middle" style="margin-right:5px"/>
            <?php echo $this->__("Starting profile execution, please wait...");?>
            </li>
            <li style="background-color:#FFD;">
            <img src="<?php echo $this->getSkinUrl('images/fam_bullet_error.gif');?>" class="v-middle" style="margin-right:5px"/>
            <?php echo $this->__("Warning: Please do not close the window during exporting data");?>
        </li>
    </ul>

    <?php if (1/*$this->getProfile()->getId()*/):?>
    <ul id="profileRows">
        <?php foreach ($this->getExceptions() as $exceptionInfo):?>
            <li style="<?php echo $exceptionInfo['style'];?>">
                <img src="<?php echo $exceptionInfo['src'];?>" class="v-middle"/>
                <?php echo $exceptionInfo['message'];?>
                <?php if ($exceptionInfo['position']):?>
                    <small>(<?php echo $exceptionInfo['position'];?>)</small>
                <?php endif;?>
            </li>
        <?php endforeach;?>
            <li id="liFinished" style="display:none;">
            <img src="<?php echo $this->getSkinUrl('images/note_msg_icon.gif');?>" class="v-middle" style="margin-right:5px"/>
            <?php echo $this->__("Finished profile execution.");?>
            </li>
            </ul>
                <script type="text/javascript">
                    var countOfStartedProfiles = 0;
                    var countOfUpdated = 0;
                    var countOfError = 0;
                    var importData = [];
                    var totalRecords = <?php echo $this->getFlowItemsCount();?>;
                    var config= <?php echo $this->getFlowConfigJson();?>;
                </script>
                <script type="text/javascript">
                    function addImportData(data) {
                        importData.push(data);
                    }

                    function execImportData() {
                        if (importData.length == 0) {
                            //$("updatedRows_img").src = config.styles.message.icon;
                            //$("updatedRows").style.backgroundColor = config.styles.message.bg;
                            Element.insert($("liFinished"), {before: config.tpl.evaluate({
                                style: "background-color:"+config.styles.message.bg,
                                image: config.styles.message.icon,
                                text: config.tplSccTxt.evaluate({updated:(countOfUpdated-countOfError)}),
                                id: "updatedFinish"
                            })});

                            if ($("liBeforeFinish")) {
                                Element.insert($("liFinished"), {before: $("liBeforeFinish")});
                                $("liBeforeFinish").show();
                            }

                            new Ajax.Request("<?php echo $this->getUrl('*/*/flowFinish');?>", {
                                method: "post",
                                parameters: {form_key: FORM_KEY,store: <?php echo $this->getRequest()->getParam('store') ?>},
                                onComplete: function(transport) {
                                    if (transport.responseText.isJSON()) {
                                        var response = transport.responseText.evalJSON();
                                        if (response.error) {
                                            Element.insert($("liFinished"), {before: config.tpl.evaluate({
                                                style: "background-color:"+config.styles.error.bg,
                                                image: config.styles.error.icon,
                                                text: response.error.escapeHTML(),
                                                id: "error-finish"
                                            })});
                                        }
                                        else if(response.filename)
                                        {
                                        	$("liFinished").update('<?php echo $this->__("Finished profile execution.");?> URL: <a href="'+response.filename+'" target="_blank">'+response.filename+' </a>');
                                            
                                        }   
                                            
                                        
                                    }

                                    if ($("before-finish-wait-img")) {
                                        $("before-finish-wait-img").hide();
                                    }

                                    $('liFinished').show();
                                }
                            });
                        } else {
                            sendImportData(importData.shift());
                        }
                    }

                    function sendImportData(data) {

                    	totalRecords = data.nbProducts;
                        
                        if (!config.tpl) {
                            config.tpl = new Template(config.template);
                            config.tplTxt = new Template(config.text);
                            config.tplSccTxt = new Template(config.successText);
                        }
                        if (!$("updatedRows")) {
                            Element.insert($("liFinished"), {before: config.tpl.evaluate({
                                style: "background-color: #FFD;",
                                image: config.styles.loader,
                                text: config.tplTxt.evaluate({offset:data.offset, updated:0, percent:getPercent(0),savedRows:totalRecords}),
                                id: "updatedRows_"+data.offset
                            })});
                        }
                        countOfStartedProfiles++;
                        if (!data.form_key) {
                            data.form_key = FORM_KEY;
                        }

                        new Ajax.Request("<?php echo $this->getUrl('*/*/flowRun');?>", {
                          method: "post",
                          parameters: data,
                          onSuccess: function(transport) {
                            countOfStartedProfiles --;
                            countOfUpdated += data["nbProducts"];//data["rows[]"].length;
                            if (transport.responseText.isJSON()) {
                                addProfileRow(transport.responseText.evalJSON());
                            } else {
                                Element.insert($("updatedRows"), {before: config.tpl.evaluate({
                                    style: "background-color:"+config.styles.error.bg,
                                    image: config.styles.error.icon,
                                    text: transport.responseText.escapeHTML(),
                                    id: "error-" + countOfStartedProfiles
                                })});
                                countOfError += data["nbProducts"];//data["rows[]"].length;
                            }

                            execImportData();
                          }
                        });
                    }

                    function getPercent(countOfUpdated) {
                        return Math.ceil((countOfUpdated/totalRecords)*1000)/10;
                    }

                    function addProfileRow(data) {
                        if (data.errors.length > 0) {
                            for (var i=0, length=data.errors.length; i<length; i++) {
                                Element.insert($("updatedRows_"+data.offset), {before: config.tpl.evaluate({
                                    style: "background-color:"+config.styles.error.bg,
                                    image: config.styles.error.icon,
                                    text: data.errors[i],
                                    id: "id-" + (countOfUpdated + i + 1)
                                })});
                                countOfError ++;
                            }
                        }
                        $("updatedRows_"+data.offset+"_status").update(config.tplTxt.evaluate({offset:data.offset ,updated:data.savedRows, percent:getPercent(data.savedRows),savedRows:data.savedRows}));
                        $("updatedRows_"+data.offset+"_img").src = config.styles.message.icon;
                        $("updatedRows_"+data.offset).style.backgroundColor = config.styles.message.bg;
                    }
                </script>
                <?php $importData = $this->getImportData();?>
                <script type="text/javascript">
                    <?php foreach ($importData as  $importValue):?>
                    addImportData(<?php echo $this->jsonEncode($importValue);?>);
                    <?php endforeach;?>
                    execImportData();
                </script>

            <?php if ($this->getShowFinished()):?>
                <script type="text/javascript">$('liFinished').show();</script>
            <?php endif;?>
   <?php endif;?>
