<br/>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td><h3><?php echo $this->htmlEscape($this->__('ShoppingFlux order import')) ?></h3></td>
            <td class="form-buttons"></td>
         </tr>
    </table>
</div>
<table class="form-list">
    <tr>
        <td class="scope-label">
            <button onclick="setLocation('<?php echo $this->jsQuoteEscape($this->getImportOrdersUrl()) ?>')" type="button" class="scalable"><span><?php echo $this->htmlEscape($this->__('Import new ShoppingFlux orders')) ?></span></button>
        </td>
        <td class="scope-label">
            <?php echo $this->htmlEscape($this->__('Will import pending ShoppingFlux orders')) ?>
        </td>
</table>