<div class="notification-global notification-global-sf">
<?php
    echo $this->__(
        '<strong>Shopping Feed is installed!</strong> <b>Attention : </b><a href="%s">Click here to finish account setup.</a>',
        $this->getUrl(
            'adminhtml/system_config/edit',
            array(
                'section' => 'shoppingflux',
                'store' => Mage::app()->getDefaultStoreView()->getCode(),
                'website' => Mage::app()->getDefaultStoreView()->getWebsite()->getCode(),
            )
        )
    );
?>
</div>
