<?php 
$this->setPriceDataObject($this->getSource());
$_feesShoppingFlux = (float) $this->getSource()->getFeesShoppingflux();

if (!$_feesShoppingFlux):
    $_feesShoppingFlux = (float) $this->getSource()->getOrder()->getFeesShoppingflux();
endif;
?>
<?php if ($_feesShoppingFlux): ?>
    <tr class="shoppingflux">
        <td class="label a-right" <?php echo $this->getColspan() ? 'colspan="' . $this->getColspan() . '"' : '' ?>>
            <?php echo Mage::helper('profileolabs_shoppingflux')->formatFeesDescription($_feesShoppingFlux, $this->getSource()->getOrder()->getMarketplaceShoppingflux()) ?>
        </td>
        <td class="a-right">
            <?php echo $this->displayPrices($_feesShoppingFlux, $_feesShoppingFlux) ?>
        </td>
    </tr>
<?php endif; ?>
